


#define AEGIS_VERSION_MAJOR     0
#define AEGIS_VERSION_MINOR     1
#define AEGIS_VERSION_REVISION  0

#define ASIO_STANDALONE
#define ASIO_HAS_STD_ATOMIC
#define ASIO_HAS_STD_CHRONO
#define _WEBSOCKETPP_CPP11_STL_
#define BOOST_DATE_TIME_NO_LIB
#define BOOST_REGEX_NO_LIB